version: '3.1'

services:
  web:
    image: nginx:1.19.2-alpine
    ports:
        - "8080:80"
    volumes:
        - ./www:/src
        - ./config/default.conf:/etc/nginx/conf.d/default.conf
        - ./logs/:/var/log/
    links:
      - php

  php:
    image: php:7-fpm
    volumes:
      - ./www:/src

  mysql:
    image: mysql:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080
